### ISSUE TITLE
ModuleNotFoundError: No module named 'pyquil.parameters'

### ISSUE THREAD

**Issue by AlreadyTakenJonas** [alecbrick/shor#1]
@alecbrick The code calls a deprecated file. parameters.py is no longer available. quilatom.py serves it's function. I changed the corresponding import call and attached the file in case you like to add it to your repository. I ran the code on Ubuntu 18.04.4 LTS and it works.
Reference: https://github.com/rigetti/pyquil/blob/3eb7ec834dd087df132371a710ca68d63ae5df46/pyquil/parameters.py
[shor.py.txt](https://github.com/alecbrick/shor/files/4475928/shor.py.txt)

**Comment by alecbrick** [comment]
Thanks! I’m not sure if anyone’s actually going to be running this code in the future, but it’s probably best to have working code here.

**Comment by AlreadyTakenJonas** [comment]
Yeah, you're right. It will take a lot of time to build the hardware needed for this to work. I only stumbled over it, because I was curious how quantum gates and algorithms are implemented in soft- and hardware. Thanks for the code!

**Comment by alecbrick** [comment]
Fixed it. Thanks for letting me know!
